[package]
name = "minimal-error"
version = "0.1.0"
authors = ["Tiago Nascimento <tiago@theosirian.com>"]
edition = "2018"

[dependencies]
bytemuck = "1.2"
cgmath = "0.17"
futures = "0.3"
image = "0.23"
nalgebra = "0.18"
num = "0.2"
wgpu = "0.5"
winit = "0.22"
